title: Hugh O'Cpnnor # your name (or website title) here
logo: "/images/Hugh_with_dirt.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master's Student at UMBC 
  <br><br>
  Studying Geogrpahy and Environmental Systems 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
